version: '3.8'
services:
  app:
    image: address-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/address
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: address
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: